### ISSUE TITLE
Car Scrapping Error 

### ISSUE THREAD

**Issue by ArcAnumgb** [oosayeroo/qb-miniheists#2]
After scrapping a car i get the following error on the console.
Latest qb, Latest version of Miniheists

[script:qb-miniheists] SCRIPT ERROR: @qb-miniheists/server/main.lua:114: attempt to index a function value (global 'Player')
[script:qb-miniheists] > handler (@qb-miniheists/server/main.lua:114)

**Comment by oosayeroo** [comment]
fixed with new update
